### PR TITLE
Implemented response object

### PR DESCRIPTION
**Pull request by flesler**
Merged next and links on a response object
Exposed several more attributes on the response object
Updated docs
Updated tests
Updated CHANGELOG
Bumped to 2.0.0

### CODE REVIEW

**Comment by flesler** [comment]
Hi @jprichardson, builds pass, added tests and docs.
Can you check and approve?

**Comment by jprichardson** [comment]
Looks good. Please remove the bump in the package.json though. I like to do that in a separate commit :) Thanks for your help! (PS: sent you an email)

**Comment by flesler** [comment]
Done

**Comment by jprichardson** [comment]
Thanks!

**Pull request merged**
