### PR TITLE
Added timeframe property to allow finer-grained search. Modified URL and newURL accordingly

### PR DESCRIPTION
**Pull request by uncleoptimus**
Playing with google search urls and thought this is super useful.
Source: http://www.webdistortion.com/2012/02/19/need-a-more-realtime-google-search-try-this-hack/
Gist:
add param to url: 'tbs=qdr:time_val'

Updated README with more info.

### CODE REVIEW

**Comment by jprichardson** [comment]
I like this, but please make the following modifications:

1. Needs to be optional. i.e. only if `resultsTimeFrame` is set should the url include the `tbs=qdr:time_val`.
2. Please add a test. Maybe just a simple as demonstrating the modified url would be sufficient.
3. Prefer you to squash the README commits into one. Should be a simple rebase interactive.

**Comment by uncleoptimus** [comment]
Sure thing, I'll see what I can do. Pretty new to web development so github is borderline Magic to me!

**Comment by uncleoptimus** [comment]
OK went ahead and:
- added test: simply runs several time-filtering queries in a loop and assures that results are returned.
- By default the url is not touched unless User has set the resultsTimeFrame prop.

Also I learned a bit about the power of rebase. Cheers!

**Comment by jprichardson** [comment]
Ok, almost there :) But now there is no update to the README file at all? The README docs were good, it's just that there were multiple commits to the README when there should of only been one. Just add this new feature to the README and then I'll merge :) Thanks!

**Comment by uncleoptimus** [comment]
Ah, I think it got Rebased out of existence. Hopefully taken care of. 
BTW, I hope I didn't break the tests! The last test (setting language etc) keeps failing but I am PRETTY SURE I didn't touch it...

**Comment by jprichardson** [comment]
Hmm, maybe because so many requests are being made so quickly and google is blocking? What happens if you open three console windows and run the tests three times simultaneously, does one of them fail?

**Comment by uncleoptimus** [comment]
Wow. That took WAY longer to fix than I care to admit hahah. I was calling 'done' multiple times. Fixed test case and all tests should pass.

**Comment by jprichardson** [comment]
I renamed `resultsTimeFrame` to `timeSpan`. Thanks, published :)

**Comment by uncleoptimus** [comment]
Cheers for the useful tool!

**Pull request merged**
