### PR TITLE
(feature) Also return body

### PR DESCRIPTION
**Pull request by DomiR**

### CODE REVIEW

**Comment by flesler** [comment]
+1

I'd like to (in addition to links) extract the "card" google adds on top for known questions.
Exposing the body could make this possible without having you implement the scrapping.

May I suggest you pass the cheerio instance (`$`) rather than `body`, else one needs to re-require cheerio on the outer project to do that extra scrapping.

**Comment by DomiR** [comment]
@flesler I added the cheerio instance :+1: 
@jprichardson please merge, this is a trivial change...

**Comment by flesler** [comment]
Actually, I think https://github.com/jprichardson/node-google/issues/10#issuecomment-190263024 would be a better approach.

**Comment by jprichardson** [comment]
I'd be in favor of @flesler proposal and would accept a PR for that. @DomiR if you'd like to see this change, please update the docs as well. Thanks.

**Comment by flesler** [comment]
I hope you don't mind, I forked and I'm building an alternative PR from scratch with a single `res` object, bumped version to 2.0.0 because it's not backwards compatible, updating docs and tests as well

**Comment by flesler** [comment]
Proposed a solution, with docs and tests updated on #38

**Comment by flesler** [comment]
@jprichardson you should be able to close this now

**Pull request closed without merging**
