### PR TITLE
updated to support http or https protocols

### PR DESCRIPTION
**Pull request by N7down**
Updated node-google to support http or https protocols
- Updated node-google library file
- Updated readme.md for instructions on how to use this feature
- This pull request fixes issue [#40](https://github.com/jprichardson/node-google/issues/40)
- This feature is also need to fix issue [#58 - how2](https://github.com/santinic/how2/issues/58) which uses this library

### CODE REVIEW

**Comment by jprichardson** [comment]
Thank you. Please squash and fix Travis issues.

**Comment by N7down** [comment]
No problem, still trying to understand why I am getting this error on line 103 of the test cases. Seems like the allLinks.length is returning an 8 instead of 10, hence the error. Any suggestions?

**Comment by N7down** [comment]
When I run the tests on the master branch it fails on that test case as well. Please see uploaded screenshot.

screenshot of master branch tests 

Seems like the allLinks.length is return 8 instead of 10 on the master branch as well.

**Comment by jprichardson** [comment]
I didn't investigate it, I just fixed the test - so I'm not sure at the moment. Thanks again. Published.

**Pull request merged**
